# Generated by Django 6.0.3 on 2026-03-26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gyms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gym",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="gyms/covers/"),
        ),
        migrations.AddField(
            model_name="gym",
            name="primary_color",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]

