# Generated by Django 6.0.3 on 2026-03-28 06:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_gymrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymFeatureConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('enable_google_auth', models.BooleanField(default=True)),
                ('enable_whatsapp_otp', models.BooleanField(default=True)),
                ('enable_email_login', models.BooleanField(default=True)),
                ('enable_reminders', models.BooleanField(default=True)),
                ('gym', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_config', to='gyms.gym')),
            ],
            options={
                'verbose_name': 'Gym Feature Config',
                'verbose_name_plural': 'Gym Feature Configs',
            },
        ),
    ]
