# Generated by Django 6.0.3 on 2026-03-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0004_gymfeatureconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='is_configured',
            field=models.BooleanField(default=False),
        ),
    ]
