# Generated by Django 6.0.3 on 2026-03-28 07:33

from django.db import migrations


def forward_migration(apps, schema_editor):
    Gym = apps.get_model("gyms", "Gym")
    GymFeatureConfig = apps.get_model("gyms", "GymFeatureConfig")

    # Clean up obsolete global configs and get a reference
    # We delete it because global config concept is removed
    global_config = GymFeatureConfig.objects.filter(gym__isnull=True).first()
    
    # Store settings to migrate if they were set globally
    enable_google = global_config.enable_google_auth if global_config else False
    enable_whatsapp = global_config.enable_whatsapp_otp if global_config else False
    enable_email = global_config.enable_email_login if global_config else True
    enable_reminders = global_config.enable_reminders if global_config else False

    GymFeatureConfig.objects.filter(gym__isnull=True).delete()

    for gym in Gym.objects.all():
        gym.is_configured = True
        gym.save(update_fields=["is_configured"])
        
        # Explicit link for all existing gyms ensuring one-to-one compliance
        if not GymFeatureConfig.objects.filter(gym=gym).exists():
            GymFeatureConfig.objects.create(
                gym=gym,
                enable_google_auth=enable_google,
                enable_whatsapp_otp=enable_whatsapp,
                enable_email_login=enable_email,
                enable_reminders=enable_reminders
            )

class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0005_gym_is_configured'),
    ]

    operations = [
        migrations.RunPython(forward_migration, reverse_code=migrations.RunPython.noop),
    ]
