# Generated by Django 6.0.3 on 2026-03-28 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0006_auto_20260328_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymfeatureconfig',
            name='gym',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feature_config', to='gyms.gym'),
        ),
    ]
