# Generated by Django 6.0.3 on 2026-03-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0007_alter_gymfeatureconfig_gym'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='branding_image',
            field=models.ImageField(blank=True, null=True, upload_to='gyms/branding/'),
        ),
    ]
