# Generated by Django 6.0.3 on 2026-03-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0008_gym_branding_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='full_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
