# Generated by Django 6.0.3 on 2026-03-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0009_gym_full_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymfeatureconfig',
            name='enable_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gymfeatureconfig',
            name='expiry_reminder_days',
            field=models.PositiveIntegerField(default=7, help_text='Days before expiry to send reminder'),
        ),
    ]
