# Generated by Django 6.0.3 on 2026-03-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0010_gymfeatureconfig_enable_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
