# Generated by Django 6.0.3 on 2026-03-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0011_gym_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='dev_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='prod_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
