# Generated by Django 5.2 on 2026-04-02 06:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0013_gym_owner_gymrequest_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('next_maintenance', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('under_maintenance', 'Under Maintenance'), ('broken', 'Broken'), ('retired', 'Retired')], default='operational', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Equipment',
            },
        ),
    ]
