# Generated by Django 5.2 on 2026-04-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0015_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymrequest',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gymrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
