# Generated by Django 5.2 on 2026-04-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0016_gymrequest_owner_name_gymrequest_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='theme_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
