# Generated by Django 5.2 on 2026-05-01 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0019_gymfeatureconfig_enable_email_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='gym',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='gyms.gym'),
            preserve_default=False,
        ),
    ]
