# Generated by Django 5.2 on 2026-05-01 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0020_equipment_gym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='gyms.gym'),
        ),
    ]
