# Generated by Django 6.0.3 on 2026-03-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='expiry_days_before',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
