# Generated by Django 5.2 on 2026-04-30 11:21

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notificationlog'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='notificationlog',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameIndex(
            model_name='notificationlog',
            new_name='notificatio_gym_id_ba94a1_idx',
            old_name='notif_log_gym_event_status_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationlog',
            new_name='notificatio_gym_id_ac8483_idx',
            old_name='notif_log_gym_channel_date_idx',
        ),
    ]
