from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.units import inch
from django.core.files.base import ContentFile

def generate_manual_pdf(manual_instance):
    """
    Generates a PDF file for a UserManual instance and saves it to the 'file' field.
    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=18)
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'MainTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor("#1e293b"),
        spaceAfter=30,
        alignment=1 # Center
    )
    
    section_title_style = ParagraphStyle(
        'SectionTitle',
        parent=styles['Heading2'],
        fontSize=16,
        textColor=colors.HexColor("#334155"),
        spaceBefore=20,
        spaceAfter=10
    )
    
    content_style = ParagraphStyle(
        'Content',
        parent=styles['Normal'],
        fontSize=11,
        leading=16,
        textColor=colors.HexColor("#475569"),
        spaceAfter=12
    )

    elements = []
    
    # Title
    elements.append(Paragraph(manual_instance.title, title_style))
    elements.append(Spacer(1, 0.5 * inch))
    
    # Role Badge
    role_name = manual_instance.get_role_display()
    elements.append(Paragraph(f"Official Guide for <b>{role_name}</b>", content_style))
    elements.append(Spacer(1, 0.2 * inch))
    
    # Intro
    elements.append(Paragraph("Welcome to the Gym SaaS platform. This guide will walk you through your available features and how to maximize your experience.", content_style))
    elements.append(Spacer(1, 0.3 * inch))

    # Sections from JSON
    for section in manual_instance.content:
        title = section.get('title', 'Untitled Section')
        body = section.get('content', '')
        
        elements.append(Paragraph(title, section_title_style))
        # Handle newlines in body
        for para in body.split('\n'):
            if para.strip():
                elements.append(Paragraph(para, content_style))
    
    # Footer
    elements.append(Spacer(1, 1 * inch))
    elements.append(Paragraph("Generated by ForYou Gym SaaS Platform", styles['Italic']))

    doc.build(elements)
    
    # Save to model
    filename = f"manual_{manual_instance.role}.pdf"
    manual_instance.file.save(filename, ContentFile(buffer.getvalue()), save=False)
    manual_instance.save(update_fields=['file', 'updated_at'])
    buffer.close()
