# Generated by Django 6.0.3 on 2026-03-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('gym_owner', 'Gym Owner'), ('staff', 'Staff'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
