# Generated by Django 6.0.3 on 2026-03-28 06:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserManual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('owner', 'Gym Owner'), ('staff', 'Staff'), ('member', 'Member')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.JSONField(default=list, help_text="List of section objects: [{'title': '...', 'content': '...'}]")),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
