# Generated by Django 6.0.3 on 2026-03-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usermanual'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanual',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='manuals/'),
        ),
    ]
