# Generated by Django 6.0.3 on 2026-03-29 08:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usermanual_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('role', models.CharField(choices=[('global', 'Global / All Roles'), ('super_admin', 'Super Admin Only'), ('owner', 'Gym Owner Only'), ('staff', 'Staff Only'), ('member', 'Member Only')], default='global', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
