# Generated by Django 6.0.3 on 2026-03-31 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_supportconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportconfig',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='supportconfig',
            name='question',
        ),
        migrations.AddField(
            model_name='supportconfig',
            name='keyword',
            field=models.CharField(default='temp_keyword', help_text='Trigger word/phrase', max_length=255),
        ),
        migrations.AddField(
            model_name='supportconfig',
            name='response',
            field=models.TextField(default='temp_response'),
        ),
    ]
