# Generated by Django 6.0.3 on 2026-03-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_supportconfig_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportconfig',
            name='keyword',
            field=models.CharField(help_text='Trigger word/phrase', max_length=255),
        ),
        migrations.AlterField(
            model_name='supportconfig',
            name='response',
            field=models.TextField(),
        ),
    ]
