# Generated by Django 6.0.3 on 2026-04-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_supportconfig_keyword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportconfig',
            name='keyword',
            field=models.TextField(help_text='Trigger word/phrase'),
        ),
        migrations.AlterField(
            model_name='supportconfig',
            name='role',
            field=models.CharField(blank=True, choices=[('global', 'Global / All Roles'), ('super_admin', 'Super Admin Only'), ('owner', 'Gym Owner Only'), ('staff', 'Staff Only'), ('member', 'Member Only')], default='global', max_length=20, null=True),
        ),
    ]
