# Generated by Django 5.2 on 2026-04-04 12:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_supportconfig_keyword_alter_supportconfig_role'),
        ('gyms', '0018_gym_status_alter_gym_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('target', models.CharField(help_text='target_role for this node', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_nodes', to='gyms.gym')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
